
# Project settings
# =================

## Development server
host: 0.0.0.0
port: 8080

## Ignore the views listed here in the _index
views_list_ignore:
  - base.html

## Do not process files with these extensions as jinja templates
plain_text:
  - .js

## Enabled pre-processors
pre_processors: 
  - scss
  - less
  - coffee
  - markdown

## Enabled post-processors
post_processors: 
  - pygments
  - typogrify

